---
  language: generic
  sudo: required
  services:
    - docker
  addons:
    apt:
      packages:
        - docker-ce
        - parallel
  script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - ./scripts/cibuild.sh
